name: chatie
description: "app with chat features"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  sign_in_button: ^3.2.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.5
  cloud_firestore: ^4.17.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  firebase_storage: ^11.7.2
  emoji_picker_flutter: ^2.2.0
  firebase_messaging: ^14.9.1
  http: ^1.2.1
  flutter_notification_channel: ^3.1.0
  image_gallery_saver: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/add_image.png
    - assets/add_image_camera.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"




  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
