// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSA5Yn_Dh9mR4hFnTaYFpf7bpLBLZqCG4',
    appId: '1:183782652:web:165a23fbd512888cafdb79',
    messagingSenderId: '183782652',
    projectId: 'chatapp-effb6',
    authDomain: 'chatapp-effb6.firebaseapp.com',
    storageBucket: 'chatapp-effb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiL1B0958cz4Dzmzb9PwT6acGzqKgU4lM',
    appId: '1:183782652:android:e41eb0b646280737afdb79',
    messagingSenderId: '183782652',
    projectId: 'chatapp-effb6',
    storageBucket: 'chatapp-effb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjB-0raYtxpTXsB4aUgY8IuT5485WQnZU',
    appId: '1:183782652:ios:a615347b24834ef4afdb79',
    messagingSenderId: '183782652',
    projectId: 'chatapp-effb6',
    storageBucket: 'chatapp-effb6.appspot.com',
    iosBundleId: 'com.me.chatie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjB-0raYtxpTXsB4aUgY8IuT5485WQnZU',
    appId: '1:183782652:ios:a615347b24834ef4afdb79',
    messagingSenderId: '183782652',
    projectId: 'chatapp-effb6',
    storageBucket: 'chatapp-effb6.appspot.com',
    iosBundleId: 'com.me.chatie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSA5Yn_Dh9mR4hFnTaYFpf7bpLBLZqCG4',
    appId: '1:183782652:web:5ba882b98b42b8a6afdb79',
    messagingSenderId: '183782652',
    projectId: 'chatapp-effb6',
    authDomain: 'chatapp-effb6.firebaseapp.com',
    storageBucket: 'chatapp-effb6.appspot.com',
  );
}
